name: CI/CD Deploy Teste

on:
  push:
    branches:
      - feature/setup-cicd

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Atualizar pasta do servidor
        run: |
          echo "Iniciando atualização em /home/wey/tst-cdci/digital-garden"
          
          # 1. Entra direto na pasta onde o Git está configurado
          cd /home/wey/tst-cdci/digital-garden
          
          # 3. Limpa lixo ou alterações locais para não travar o pull
          git reset --hard
          
          # 4. Puxa as novidades
          git pull
          
          echo "Projeto atualizado com sucesso!"
